### ISSUE TITLE
Total and unallocated SP

### ISSUE THREAD

**Issue by zrupcic** [mgoeppner/evemon#17]
Feature request: Can we have another label beneath "Total SP" and "Free SP" with the sum of those two? There's enough free space left and it would be the easiest thing to implement.

**Comment by mgoeppner** [comment]
007cda0 adds this.

"Total SP" has been renamed to "Allocated SP"
"Free SP" has been renamed to "Unallocated SP"
A new line "Total SP" is the sum of allocated and unallocated SP

**Comment by mgoeppner** [comment]
![bild](https://user-images.githubusercontent.com/1063646/152684294-c21accfc-8070-45ab-8874-6d84a681b14e.png)
