### ISSUE TITLE
Feature Request: Add the number of skills in the skill queue next to the time remaining

### ISSUE THREAD

**Issue by doomlord289** [mgoeppner/evemon#25]
Copied from peterhaneve/evemon#290

Since the skill queue is now limited to 150 skills rather than the 24 hours it was when Evemon was first developed, I think it makes sense to display the number of skills in the queue next to the time remaining at the bottom of the character tab.

**Comment by luyi1888** [comment]
It will look like this at the bottom of the character tab:
2 days, 3 hours, 4 minutes, 5 seconds (6 skills)
And in overview tab:
Queue ends in 2 days, 3 hours, 4 minutes, 5 seconds (6 skills)
