### ISSUE TITLE
Please also consider fixing some other issues

### ISSUE THREAD

**Issue by wvdvegt** [mgoeppner/evemon#29]

**Comment by wvdvegt** [comment]
Can you please have a look at these older issues (if not fixed already)?

https://github.com/peterhaneve/evemon/issues/300 (might already be fixed)
https://github.com/peterhaneve/evemon/issues/301
https://github.com/peterhaneve/evemon/issues/302
https://github.com/peterhaneve/evemon/issues/304

I also have some private code that shows a small numeric badge on each overview tab pilots indicating the number of notifications of a pilot. (Not very comforatble with the pull request  but can make a diff).

**Comment by mgoeppner** [comment]
Hammertime disabled in 506f4a50af957c87a49dc1c407fa63c55353338a

**Comment by mgoeppner** [comment]
NTP pool fixed in 42510670fd2db842003a59a54b06691f5a9fef41

**Comment by mgoeppner** [comment]
Improved logging added in 1e8bc73bebf7f45088b1072edf9541e8c2e939ff
