### ISSUE TITLE
No character loaded

### ISSUE THREAD

**Issue by insoniak** [mgoeppner/evemon#3]
Hey. I performed a clean install of 4.1.0, added characters via file ->  add charcter and restarted the app. After restart all chars a gone and you need to add them once again. 
What information can I provide to you to look up in this issue?

**Comment by mgoeppner** [comment]
I'll take a look at this tomorrow -- I noticed some weirdness with blank file base toons as well.

**Comment by nemods** [comment]
Just to chip in here, have the same issue. Also after a clean uninstall and reinstall

**Comment by nemods** [comment]
Seems to be fixed with the 4.1.1 release :)
Thank you for taking up updating EVEMon!

**Comment by mgoeppner** [comment]
Great to hear @nemods! @insoniak does 4.1.1 fix the issue for you as well?

**Comment by insoniak** [comment]
Yes, after clean install the issue is gone. Thanks a lot!
