### ISSUE TITLE
Upstream project license not found

### ISSUE THREAD

**Issue by notmorganfreewoman** [mgoeppner/evemon#33]
The upstream project Evemon has a license at https://evemon.readthedocs.io/en/latest/about/license.html and https://github.com/evemondevteam/docs/blob/master/src/about/license.txt locations. Basically it is the MIT license with the following obligation.

___"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."___

I cannot find a copy of this upstream license in the repository.

Should this upstream license not be also included in downstream forks and substantial portions of it?

Shall you include a LICENSE file in the project that meets the upstream license obligations? It would make it 1) easy to locate and 2) explainatory by Github as part of their license UI.

See upstream issue ticket also here https://github.com/peterhaneve/evemon/issues/314

**Comment by mgoeppner** [comment]
The upstream license you are referring to is only for the docs and does not apply to the EVEMon software itself. You can find the readthedocs upstream license here: https://github.com/readthedocs/readthedocs.org/blob/master/LICENSE.

The EVEMon application itself is GPL2 licensed, with the license available in the about window and here: https://github.com/mgoeppner/evemon/blob/main/src/EVEMon.Common/Resources/License/gpl.txt. I can copy this file to LICENSE.

![bild](https://user-images.githubusercontent.com/1063646/155723882-a03f15e3-94d0-4989-93d5-192a2ae3c41a.png)

**Comment by mgoeppner** [comment]
LICENSE file created in dd6c51c.
