### ISSUE TITLE
CI-based builds

### ISSUE THREAD

**Issue by jhmartin** [mgoeppner/evemon#4]
Please consider pulling in https://github.com/peterhaneve/evemon/pull/309 and letting a public CI system perform the builds / releases, to increase confidence that nothing untoward has been slipped in.

**Comment by mgoeppner** [comment]
@jhmartin Sure -- feel free to open that PR against this fork!

**Comment by apolaskey** [comment]
@mgoeppner Can you provide some details in the readme on how to build this? Looks like a C# project but what version etc.

**Comment by mgoeppner** [comment]
It's .net 4.6.1 -- newer VS versions may require you to download this: https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net461-developer-pack-offline-installer

I'll go through the readme and update it with the necessary instructions later for building, updating the game data, and packaging later today.

**Comment by mgoeppner** [comment]
@jhmartin see #7

**Comment by jhmartin** [comment]
@mgoeppner Looks good. Of course you'll have to attach circleci to your repo. It builds and runs for me.

**Comment by mgoeppner** [comment]
@jhmartin just getting back to this now -- it appears to work for me as well. There are a few extra steps needed to build the installer -- will get those implemented and we should have a mvp ci build.

**Comment by mgoeppner** [comment]
https://app.circleci.com/pipelines/github/mgoeppner/evemon/5/workflows/9b85618a-98c3-47c6-ac09-14fb311e8a61/jobs/5

CI builds are working now and add the .zip binaries and .exe installer as artifacts.

Thanks for bringing this issue up @jhmartin!

@apolaskey #12 will track the readme updates.
