### ISSUE TITLE
notifications RE:ESI login

### ISSUE THREAD

**Issue by Commissar0617** [mgoeppner/evemon#44]
installed fresh today on 4.2.0, logged back into all my accounts as evemon hasn't been run in almost a year. still is complaining about ESI login errors, despite it working less than an hour before.

**Comment by Commissar0617** [comment]
It gives desktop notifications that esi login failed,  but when i go to evemon, it looks fine and updated fines for all chars. Does this about every 30 minutes

**Comment by mgoeppner** [comment]
Out of date, closing.
