### ISSUE TITLE
External Calender Auth issue with Google

### ISSUE THREAD

**Issue by Ka0sKontrol** [mgoeppner/evemon#45]
When you enable external calendars and try to authenticate with google it gives the danger error page (e.g., "This app is blocked
This app tried to access sensitive info in your Google Account. To keep your account safe, Google blocked this access"). Unable to use MS Outlook calendar since the option is greyed out/non-selectable. Requesting Google Auth fix.
![Evemon 4-2-0 GoogAuth_error](https://user-images.githubusercontent.com/29661611/166631581-a0f073bb-5467-4334-ac0c-4d3f11bda0be.png)

**Comment by capntack** [comment]
Same issue here. When I try to turn on access for "Less secure apps" I get this message in my Google settings: "This setting is not available for accounts with 2-Step Verification enabled. Such accounts require an application-specific password for less secure apps access" and am directed to the following help document: https://support.google.com/accounts/answer/185833?hl=en

**Comment by mgoeppner** [comment]
This needs to be solved with an app password as described in https://support.google.com/accounts/answer/185833.

**Comment by mgoeppner** [comment]
I'll dig a bit into this -- I cannot promise a resolution though, since the original integration is quite old, and predates me by at least one, probably more maintainers -- this is likely the reason google is blocking it.
