### ISSUE TITLE
File type not supported

### ISSUE THREAD

**Issue by DanielMarch** [mgoeppner/evemon#5]
After clean install and closing the app, upon reopening File type not supported notification

"The file is probably from an EVEMon version prior to 1.3.0. This type of file is no longer supported"

**Comment by phakez** [comment]
I got the same issue after a clean install. I did delete the C:\Users\your username\AppData\Roaming\EVEMon folder to get the new skills

https://i.vgy.me/jeJdlR.png is what it's showing for me. Once I launch EVEMon I do get the Data Update Popup (https://i.vgy.me/cqjRnc.png). After selecting "Remind Me Later" I get to the EVEMon Main Screen, **I can add characters, but after relaunching EVEMon all my characters are wiped again.**

**Comment by mgoeppner** [comment]
Hi @DanielMarch and @phakez! Thanks for reporting this -- I have fixed this on the main branch, and will publish an updated release later.

Cheers!
