### ISSUE TITLE
Difficulty getting Google to accept mail

### ISSUE THREAD

**Issue by poundjd** [mgoeppner/evemon#54]
HI, i love the app!
I Have not gotten my email account to allow the emails to go through.
do you have ANY hints or suggestions?

**Comment by mgoeppner** [comment]
You may need to use an app password instead of your gmail password to authenticate to gmail's smtp server -- see this: https://support.google.com/accounts/answer/185833

**Comment by poundjd** [comment]
![Screenshot 2022-12-23 194629](https://user-images.githubusercontent.com/20841262/209415758-cb7d1f8b-bbb8-4548-87d1-f74626326c79.png)

**Comment by poundjd** [comment]
Tip: Don’t create an App Password unless the app or device you want to connect to your account doesn’t have “Sign in with Google.”

Do you support this?
