### ISSUE TITLE
Certificate Browser for Resource Processing outdated.

### ISSUE THREAD

**Issue by EvE-Player** [mgoeppner/evemon#55]
As title states the certificate for Resource Processing > Reprocessing level V is largely outdated as the majority of the ores have now been grouped:

<details>
  <summary>Images showing what I mean</summary>
  
![Outdated Cert](https://user-images.githubusercontent.com/121873666/210366138-ae48df37-c6a1-4aba-ba77-fee3a033e82d.PNG)
![Patch notes, new name-group](https://user-images.githubusercontent.com/121873666/210366141-081b9472-f4c5-41ca-8a86-66896287d742.PNG)
</details>

Attached images so you can see what I mean in case I didn't explain properly. Hope you will be able to fix this. 

Also thanks for keeping this program updated!

**Comment by mgoeppner** [comment]
Certificates were an old in-game system for tracking skill development -- however they are no longer part of the game, and CCP has not been updating the SDE to reflect the old certs and new skills (but they still ship the old cert tables to prevent breaking ancient programs like evemon) -- they are still in evemon for legacy reasons, but the ingame certificate browser went the way of the dodo when CCP released the new skill window.
