### ISSUE TITLE
Can't add characters via ESI

### ISSUE THREAD

**Issue by torinavia** [mgoeppner/evemon#57]
EVEMon 4.2.2 correctly checks EVE server status, but when I tried to add a character, it gives me the error "EVEMon did not receive a valid response from the CCP SSO server. Try again in a few minutes" (despite the browser telling me the authentication was succesful). I've tested my ESI on two other machines and everything works properly. 

The PC I'm having issues with has Windows 7 Service Pack 1, the other two are Windows 10, could this have something to do with it? I have no trouble authenticating other EVE tools like pyfa or Short Circuit on the same machine and the issue persists even after adding inbound and outbound rules in Windows Firewall or disabling it temporarily.

I'm at a loss here, what could be the problem?

**Comment by lang-ri** [comment]
I've been having the same issue. I get the same error on my home computer which runs on Windows 7 SP1. All the other 3rd party tools that I use work without issues. On my work computer (Win 11) there's no issue, everything works well and I can add characters without any problems.

**Comment by NevarrTivianne** [comment]
If I had to guess I'd say one of the .net libraries is relying on something in Win7 for SSL and the EVE website uses either a more (too) modern Cypher or some other SSL feature.

BTW, meanwhile CCP announced that support for Windows 7 will end on Dec 7 - https://www.eveonline.com/news/view/support-for-windows-7-and-8-will-end-soon

**Comment by mgoeppner** [comment]
Closing since this issue is stale.

Unfortunately, windows 7 is unsupported.
