### ISSUE TITLE
EVEMon 4.2.2 unable to do anything as freezes

### ISSUE THREAD

**Issue by BigIron149** [mgoeppner/evemon#73]
Hey :)

Trying to use [EVEMon 4.2.2](https://github.com/mgoeppner/evemon/releases/tag/4.2.2), and when I try to do anything on the skill plan side of things the app just freezes, it's still active on task manager and the CPU Usage/Ram Usage keeps going higher and higher? 
Any ideas Seems okay on the main page but goes weird on the skill pages for me. 

Cheers :)

**Comment by mgoeppner** [comment]
This is likely caused by evemarketer, which is dead -- you can try setting the market provider to fuzzworks in settings, or use 5.x.x where evemarketer is fully removed.
